### ISSUE TITLE
API test not passing when res.send('some text') is used

### ISSUE THREAD

**Issue by james-wallis** [RuntimeTools/chai-openapi-response-validator#29]
**OpenAPI version**
3

**Describe the bug**
Testing an express application.
I have an endpoint which uses `res.send()` to  send a `404` and an error message back to the client. The API spec I have created specifies that the response should be `text/html` but the test is failing. I've also tried `text/plain` but the test also fails.

If I change the endpoint to use `res.json()` and the response type to be `application/json` the test passes.

**Screenshots**
![image](https://user-images.githubusercontent.com/17385115/69967776-0625f680-1511-11ea-88f9-17455790897d.png)

**Additional context**

**Comment by rwalle61** [comment]
At first glance I agree this is a bug with us. The [Express docs for `res.send`](https://expressjs.com/en/api.html#res.send) say that >When the parameter is a String, the method sets the Content-Type to “text/html”

I'm a bit busy until xmas but anyone is welcome to submit a PR

**Comment by rwalle61** [comment]
To clarify, it looks like the server code resembles 
```js
res.status(404).send('http://something...does not exist')
```
and the test code resembles 
```js
const res = chai.request(app).get(path); // chai and supertest both use superagent, which writes strings to res.text, leaving res.body as {}
expect(res).to.satisfyApiSpec;
```

In that case, `res` has header `text/html`, body `{}`, text `'http://something...does not exist'`.

I will add the test cases and resolve this
