### ISSUE TITLE
method to set new specs file when needed

### ISSUE THREAD

**Issue by rolfisub** [RuntimeTools/chai-openapi-response-validator#44]
**OpenAPI version**
2 and 3

**Is your feature request related to a problem? Please describe.**
No, but it would be nice to be able to test one OpenAPI file after another on a single test run. Currently, the only workaround would be to call mocha per test file, so that the chai plugins gets reset for each run.

**Describe the solution you'd like**
It would be nice to have a method to set the new file, something like`setSpecFilePath` so that you can specify a new specs file when it is needed.

**Describe alternatives you've considered**
The only alternative that I have considered is to call mocha per test file using a shell script, which I rather not have to maintain. Maybe there are other alternatives?

**Additional context**
If you have multiple OpenAPI specs on a single codebase (microservices architecture) example:
```
service1.yml
service1.spec.ts
service2.yml
service2.spec.ts

// run with ts-mocha *.spec.ts
// that would call all the files but maintain chai context
// this could fail because as soon as service2.spec.ts gets read
// it resets the spec yml file, so when service1.spec.ts test gets to run its
// actually running against service2.yml file 
```

let me know if you need more information

**Comment by rolfisub** [comment]
actually, by installing the plugin on a `before` call with mocha it solves the issue

**Comment by rolfisub** [comment]
actually you can use `before`  and the first test will run as normal, but now the second test will be checked against service1 and fail. so I guess this request could still be valid?

**Comment by rwalle61** [comment]
Thanks for raising this!

I haven’t had chance to look at this properly, but your mention of `before` reminds me of a (maybe) similar problem I ran in to while trying to test the assertions. Does loading the API specs like in `satisfyApiSpec.test.js` solve this?

If not, please post an example test file (especially how you do `chai.use(chaiResValidator(pathToApiSpec))` and I’ll recreate this when I get time :)

**Comment by rwalle61** [comment]
Also happy to review a PR

**Comment by rolfisub** [comment]
Hi @rwalle61 seems this was a false alarm if you use `mocha.before` or `mocha.beforeEach` to install the plugin with a new schema file it works for the corresponding tests.
