### ISSUE TITLE
Falsey body values are incorrectly failing validation

### ISSUE THREAD

**Issue by AlexDobeck** [RuntimeTools/chai-openapi-response-validator#49]
**OpenAPI version**
OpenApi 2 and OpenApi 3

**Describe the bug**
'false' response bodies are failing validation in OpenApi 2 and OpenApi 3.
nullable responses bodies are failing validation in OpenApi 3

**To Reproduce**
Steps to reproduce boolean failure:
1. Create a spec with a boolean body response (OpenApi2/OpenApi3)
2. Attempt to validate a 'false' response
3. Notice the validation fails

Steps to reproduce nullable failure:
1. Create a spec with a nullable body response (OpenApi3)
2. Attempt to validate a null response
3. Notice the validation fails 

**Expected behavior**
null and false values should be valid response bodies as allowed by the OpenApi specs

**Comment by AlexDobeck** [comment]
I have submitted a PR I believe will resolve this issue:
https://github.com/RuntimeTools/chai-openapi-response-validator/pull/50

**Comment by rwalle61** [comment]
Released, I'll let you close

**Comment by AlexDobeck** [comment]
Excellent, thanks for the fast turn-around.
