### ISSUE TITLE
Error: Invalid Chai property

### ISSUE THREAD

**Issue by kingLotzi** [RuntimeTools/chai-openapi-response-validator#5]
Hi! I've been trying to run the example code, but I'm getting an error

  1) GET /example/request should satisfy swagger.json spec:
     Error: Invalid Chai property: satisfyApiSpecForStatus

Any reason why could be that? 

Here is my simple code:

const chai = require('chai');
const expect = chai.expect;
const chaiResponseValidator = require('chai-openapi-response-validator');

chai.use(chaiResponseValidator('_some_url_/swagger.json'));

describe('GET /example/request', function() {
    it('should satisfy swagger.json spec', async function() {

      const res = {
        // Response includes:
            status: 200,
            body: {
              string: 'string',
              integer: 123,
            },
        };
      console.log(res);
      // Assert that the HTTP response satisfies the OpenAPI spec
      expect(res).to.satisfyApiSpecForStatus(200);
      console.log('aca llego');
      // Alternative assertion
      expect(res).to.have.status(200).and.satisfyApiSpec;
    });
  });

Thanks !

**Comment by rwalle61** [comment]
Hi, cheers for trying us out! 

`expect(res).to.satisfyApiSpecForStatus(200)` is no longer supported - you should use `expect(res).to.have.status(200).and.satisfyApiSpec` instead.

**Comment by kingLotzi** [comment]
Hi! Thanks for the early response! 
Before continuing with the issue, here is the link from where I follow the installation guide and the example:
https://www.chaijs.com/plugins/chai-openapi-response-validator/


In other hand, my code now looks like this:

const chai = require('chai');
const expect = chai.expect;
const chaiResponseValidator = require('chai-openapi-response-validator');

chai.use(chaiResponseValidator('some_url/swagger.json'));

describe('GET /example/request', function() {
    it('should satisfy swagger.json spec', async function() {
      // Get an HTTP response (e.g. via chai-http or supertest)
      // chai.use(require('chai-http'));
      const res = {
        // Response includes:
            status: 200,
            body: {
              string: 'string',
              integer: 123,
            },
        };
      // Alternative assertion
      expect(res).to.have.status(200).and.satisfyApiSpec;
    });
  });

but the error stills persist
  1) GET /example/request should satisfy swagger.json spec:
     Error: Invalid Chai property: status

Sorry for the inconvenience and thanks for the help!

**Comment by rwalle61** [comment]
Thanks for the link, I'll get Chai's page updated.

Re. your error, I think it's because you've commented out `chai.use(require('chai-http'));`. The `expect(Foo).to.have.status(Bar)` assertion is chai-http's (see https://www.chaijs.com/plugins/chai-http/ for examples). So either require it (by uncommenting that), or don't use `have` by changing your assertion to
```js
expect(res.status).to.equal(200);
expect(res).to.satisfyApiSpec;
```

Let me know if that solves your problem. 

I'll update our docs to make clearer that you need to do `chai.use(chai-http)`, or split the line into 1

**Comment by rwalle61** [comment]
I've updated our docs accordingly: https://github.com/RuntimeTools/chai-openapi-response-validator#1-given-a-test-file

**Comment by kingLotzi** [comment]
Excellent! The problem was solved so i will close this thread.

Just FYI i'll like to suggest you some updates regarding the path of the endpoint, almost always, this path isn't static (it may change some variables) and for that it may not find it in the swagger/openapi file.
I don't know if you have think about that but maybe you can keep it in mind for future updates.

Despite that, the library works find, thanks for all!

**Comment by rwalle61** [comment]
Glad I could help.

Thanks for the tip about the path. Do you have an example of when the path changes? I may use those as test cases for a new update.
