### ISSUE TITLE
No validation when incorrect type is of allowed types

### ISSUE THREAD

**Issue by hrina** [RuntimeTools/chai-openapi-response-validator#56]
**OpenAPI version**
2

**Describe the bug**
when changing the type from array to string no error is shown. but for example if I use an incorrect value e.g. String then it throws a validation that the expected type is Array. 
Like wise even If I changing other values in the swagger e.g. string to boolean does not throw any validation.

Also I wanted to validate the response schema against the schema definition in the swagger. Is satisfySchemaInApiSpec  to be used for validating the response schema? Documentation on this will be helpful.

E.g. In below schema if I change foodDetails to string instead of array no validation is thrown.

 "schema": {
              "$ref": "#/definitions/FoodDetails"
            },

 "FoodDetails": {
      "type": "object",
      "properties": {
        "foodDetails": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/foods"
          }
        }
      }

**Comment by hrina** [comment]
My bad some issue in my schema

**Comment by rwalle61** [comment]
Feel free to reopen if you have any further issues or questions :)

Would you mind clarifying what you mean about this?
> Also I wanted to validate the response schema against the schema definition in the swagger. Is satisfySchemaInApiSpec to be used for validating the response schema? Documentation on this will be helpful.

There is an example in the README of how to use `expect(obj).to.satisfySchemaInApiSpec`. That’s meant for validating objects against schema definitions, so maybe not suitable for what you want (“validate the response schema against the schema definition in the swagger”)

Could you give an example (in pseudocode if you like) of what you'd like to do, beyond what you can do with  `expect(response).to.satisfyApiSpec` ?

**Comment by hrina** [comment]
Thanks, it is working perfectly fine now. There was a issue in my schema e.g.in schema FoodDetails , there is an object foodDetails  but in response it was returning as foodDetailsList. since there was no required properties listed, any negative scenario that I tried by messing around with the properties of foodDetails  did not result into any validation error.  Just out of curiosity if additionalProperties: false is not set in schema, is it possible for us to fail the test if we receive any other property than the one defined in the schema.
